# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3cdf0f40ddd5a23b8afa910ebe994891"
application_url = "https://gps-tmp-permission-xbox.trycloudflare.com"
embedded = true
name = "qr-app"
handle = "qr-app-136"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://gps-tmp-permission-xbox.trycloudflare.com/auth/callback",
  "https://gps-tmp-permission-xbox.trycloudflare.com/auth/shopify/callback",
  "https://gps-tmp-permission-xbox.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "test-qr-app.myshopify.com"
automatically_update_urls_on_dev = true
